### ISSUE TITLE
SConsShared/SConstruct_common.scons

### ISSUE THREAD

**Issue by Gajuharale** [fermi-lat/SConsShared#12]
AttributeError: 'SConsEnvironment' object has no attribute 'SourceCode'
I am getting an above error
While running following command
scons -C ScienceTools --site-dir=../SConsShared/site_scons --conda=$PREFIX --use-path all

Please help me 
Thanks in advance

**Comment by donhorner** [comment]
Just to be clear, I guess you are trying to build the Fermitools following the instructions on the [Contributing to the Fermitools](https://github.com/fermi-lat/Fermitools-conda/wiki/Contributing-to-the-Fermitools) page?

**Comment by Gajuharale** [comment]
Thank you for your response
Yes I am trying to install fermitools
Thank you
